spring.application.name=department
spring.config.import=optional:file:/config/department.properties,optional:file:/config/department-dev.properties,optional:file:/config/department-prod.properties

# ----- Observability -----
management.tracing.sampling.probability=1.0

management.otlp.tracing.endpoint=${OTEL_TRACES_ENDPOINT:http://otel-collector:4318/v1/traces}
management.otlp.metrics.export.url=${OTEL_METRICS_ENDPOINT:http://otel-collector:4318/v1/metrics}
management.otlp.logging.endpoint=${OTEL_LOGS_ENDPOINT:http://otel-collector:4318/v1/logs}

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers,env,mappings
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
